name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest


    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build
      - name: Generate SPM
        run: ./gradlew assembleXCFramework generateSPM

      - name: Build Swift
        run: swift build
        working-directory: ios
      - name: Run Swift tests
        run: swift test
        working-directory: ios
